# espanso match file

matches:
  # ____________________________________________
  # Scrcpy - open external display + the most stable keyboard/mouse options
  - trigger: ":scrcpy-sdk"
    replace: "scrcpy --disable-screensaver --keyboard sdk --mouse sdk --new-display"
