# Extra autostart processes
  exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
  exec-once = /usr/lib/xdg-desktop-portal-hyprland &
  exec-once = /usr/lib/xdg-desktop-portal &
  exec-once = walker --gapplication-service
  exec-once = espanso service start --unmanaged
  exec-once = surfshark
