# Extra autostart processes
  exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
  exec-once = /usr/lib/systemd/user/xdg-desktop-portal-hyprland.service &
  exec-once = /usr/lib/systemd/user/xdg-desktop-portal.service &
  exec-once = elephant && walker --gapplication-service &
  exec-once = espanso launcher
  exec-once = surfshark &
